### ISSUE TITLE
Wrapping of _id fields

### ISSUE THREAD

**Issue by dowbtxt** [art1415926535/graphene-sqlalchemy-filter#29]
Let's say we have 2 models with a relationship between them, such as:

```
class ModelA:
  modelb_id = db.Column(db.BigInteger(), db.ForeignKey('modelb.id'), nullable=True)
  modelb = db.relationship('ModelB')

class ModelB:
  name = db.Column(db.Text, ...)
  ...
```

Now, when the filter module wraps ModelA, it will automatically make the following available through GraphQL:

```
modela(...) {
  modelbId
  modelb {
    id
    name
  }
}
```

However, the value in `modelbId` will be a plain integer, rather than a global/hashed GraphQL ID like obtained when querying `modelb { id }`.

Based on that, I have two questions:

1) Is it possible to add built-in support so that all the cases like this are automatically recognized and return GraphQL IDs?

2) If it is not possible or not accepted to add this as built-in behavior to the filter module, how would one do this manually in their project?

Thanks!

**Comment by art1415926535** [comment]
First question needs to be asked in [graphene-sqlalchemy repo](https://github.com/graphql-python/graphene-sqlalchemy). I think you can create your own resolver for `modelbId` field.

It doesn't make sense to add this behavior to this module, since it doesn't generate object types from models. So far I have no idea how to correctly handle int and GlobalID in filters. But I'll think about it.

**Comment by dowbtxt** [comment]
Great, thanks for the pointers.
